### PR TITLE
Update Indonesian translation

### PR DESCRIPTION
**Pull request by cho2**
Update Indonesian translation

### CODE REVIEW

**Comment by tkashkin** [comment]
Thanks for contribution and sorry for delay.

I have updated po/pot files in `dev` branch. Can you submit a new PR for it?

There are some weird things happening with either `gettext` or meson `i18n` module, it does not find all strings for some reason. Please report if you find untranslatable strings.

**Comment by cho2** [comment]
> I have updated po/pot files in dev branch. Can you submit a new PR for it?

Sure.
Then should i pull request to `master` or `dev` branch?

**Comment by tkashkin** [comment]
Send a PR to `dev` branch.

**Comment by cho2** [comment]
#95

**Pull request closed without merging**
