### PR TITLE
Tray icon (aka AppIndicator) support

### PR DESCRIPTION
**Pull request by mjdiliscia**
Gnome ditched the system tray, but it's still useful on other DEs like KDE, Cinnamon, XFCE, etc.
I tried to generate as little coupling as I could, but maybe the way I'm getting the games information isn't as clean as it could be.
I'm open to suggestions for improving it, of course.

### CODE REVIEW

**Comment by tkashkin** [comment]
I'm not sure if indicator is really needed for GameHub and I mostly agree with GNOME and [elementary](https://elementary.io/docs/human-interface-guidelines#does-your-app-need-an-indicator) on that topic.

GameHub already implements application launcher menu via `libunity`, but it's disabled by default because `libunity` is not maintained and causes build errors.

@Lucki, @neuromancer any feedback? Is it worth implementing? Should it be enabled by default if it's implemented?

**Comment by neuromancer** [comment]
> any feedback? Is it worth implementing? Should it be enabled by default if it's implemented?

Let me test it ..

**Comment by neuromancer** [comment]
I tested this PR in Cinnamon and it looks useful to me. I don't know if it should be enabled by default (at least, in the first releases). Clicking in the tray icon will only allow basic tasks (show/hide, recent games and quit). That can be improved over time, I think.

Also, changes in the source code are relatively small.

**Comment by Lucki** [comment]
> any feedback? Is it worth implementing? Should it be enabled by default if it's implemented?

I'm using Gnome so I'm biased. I'm using Gamehub like every other program, even Steam. I'm opening it in fullscreen and let it sit on a dedicated desktop. When I want to do something with it I scroll to the desktop otherwise it's out of sight in the background or overlayed by a game.
While I don't see the benefit of having this always sitting in the tray since there's no online functionality which you would expect to be always in the background it would somehow reflect my workflow on a classic desktop layout.

At the same time I'm questioning what's so different to having it minimized? We're talking about classic desktop environments so they have a task bar where it sits. The more programs are open the more will be in the taskbar and the task size will be adjusted automatically to fit all programs not just Gamehub.

As it's optional it can't hurt to include but I definitely wouldn't make it the default. I always hated programs that stayed open when you thought you've closed them with the big upper right X.
It also probably should have _some_ benefit (haven't looked at the code) e.g. less memory consumption than having it minimized, a real reason…

…because the only reason for this PR is because…

> […] GameHub takes some time to initialize […]

…so I think that's the real thing to tackle. Gamehub admittedly still takes quite some time loading steam games and combining them but at least it isn't blocking the UI in the meantime anymore.

We could even think of auto-minimizing and re-opening Gamehub on game start and exit if that's somehow saving ressources but that needs the proper custom emulator running detection of the refactoring branch first.

**Comment by neuromancer** [comment]
> While I don't see the benefit of having this always sitting in the tray since there's no online functionality which you would expect to be always in the background it would somehow reflect my workflow on a classic desktop layout.

AFAIK, buying new GOG games while you have the app open, won't update your collection. While this is a rare use case, it could be nice to have in another PR, if the code changes are small.

**Comment by mjdiliscia** [comment]
> At the same time I'm questioning what's so different to having it minimized? We're talking about classic desktop environments so they have a task bar where it sits. The more programs are open the more will be in the taskbar and the task size will be adjusted automatically to fit all programs not just Gamehub.

Taskbars on classic desktops tends to clutter if you have many opened programs. That's in part way many launchers hide themselves in the systray, they are meant to be used from time to time and having them always in the taskbar is annoying.

I understand it doesn't have much sense in desktops like Gnome, but it does in classic ones. It's obviously your decision, but I really think having this option helps to integrate GameHub with the classic desktop workflow.

**Comment by kajlando** [comment]
I'm on Gnome so I'm biased. I'd like to see that option. I'll turn it on myself anyway though. Thanks @mjdiliscia

**Pull request closed without merging**
