### PR TITLE
Quick fix for #146

### PR DESCRIPTION
**Pull request by neuromancer**

### CODE REVIEW

**Comment by tkashkin** [comment]
I don't think it's the right way to fix it. It may break other games.

**Comment by neuromancer** [comment]
Should I add a check to verify that it is GOG game?

**Comment by neuromancer** [comment]
Fair enough. I will test it and report back the results here. In the meantime, maybe we need to create a dummy GOG/Humble accounts with free games to have CI tests. It will be a faster way to know if this fixes are useful or not..

**Comment by neuromancer** [comment]
I think this fix works fine. I don't have any example of a game broken by this.

**Pull request merged**
