### PR TITLE
Improve Flatpak executable detection and add more WINEs

### PR DESCRIPTION
**Pull request by ntninja**
Changes:

  * Drops PolicyKit support from build as that won't likely ever work from the Flatpak sandbox
  * Updates Flatpak runtime to latest version and fixes the issues caused by this
  * Fixes `$PATH` lookup of executable from inside the Flatpak sandbox (host `/usr` is mounted as `/run/host/usr`)
  * Adds auto-detection for the WINE versions provided by the WINE Debian repo (stable, staging, devel)
  * Builds `file-roller` from source and drops bundled libmanette archive in favour of external URL (as per https://github.com/tkashkin/GameHub/issues/181#issuecomment-637651373)

### CODE REVIEW

**Comment by ntninja** [comment]
@tkashkin: I've added the `file-roller` and `libmanette` build changes as per https://github.com/tkashkin/GameHub/issues/181#issuecomment-637651373.

**Comment by ntninja** [comment]
@tkashkin: Did you find time to look at this yet?

**Comment by tkashkin** [comment]
@ntninja

I'll probably merge this manually later since I've planned to change both build scripts and compatibility tools as a part of current [refactoring](https://github.com/tkashkin/GameHub/compare/dev...refactoring).

I think it would be better to merge this into the next version as it already has a lot of breaking changes and will most likely have even more.

**Comment by ntninja** [comment]
Thanks for telling, I thought `dev` was the most up-to-date thing there was!

Should I rebase onto `refactoring` then?

**Comment by tkashkin** [comment]
> Should I rebase onto `refactoring` then?

There is a lot of changes there already and there will be more changes later. I don't think it's worth to merge it now.

**Comment by ntninja** [comment]
Are you saying that you will not merge up-to-date rebased on `refactoring` at all? Or that you think doing the rebase now would be undue work for me (the contributor)?

**Pull request closed without merging**
